### ISSUE TITLE
How to configure vuepress v2.x config.ts?

### ISSUE THREAD

**Issue by vvfock3r** [meilisearch/vuepress-plugin-meilisearch#293] opened 2023-01-31 12:27 UTC
My configuration file is config.ts, not config.js. Can you help me

**Comment by bidoubiwa** [comment] 2023-01-31 12:41
Hey! Unfortunately we are not compatible with vuepress v2 and it is not planned that we will be :(

**Comment by bidoubiwa** [comment] 2023-01-31 12:43
Closing as it is a duplicate of #175

**Closed by bidoubiwa** 2023-01-31 12:43 UTC
Labels: enhancement

**Comment by TonyRL** [comment] 2023-02-27 23:29
> Hey! Unfortunately, we are not compatible with vuepress v2. We are waiting for external contributing to make it compatible.
> 
> See #175

It's not an issue with VuePress v2. VuePress v1 itself supports [TypeScript as Config](https://vuepress.vuejs.org/guide/typescript-as-config.html#overview).

**Comment by JQiue** [comment] 2024-06-07 06:03
https://github.com/JQiue/vuepress-plugin-meilisearch2/blob/main/README.md#vuepress-plugin-meilisearch2
